deployment:
  tasks:
    - export DEPLOYPATH=/home/jswplvao/piconetit.com/pos
    - /bin/cp -R maxmarketing "$DEPLOYPATH/"
    - /bin/cp -R basharair "$DEPLOYPATH/"
    - /bin/cp -R lubabahajj "$DEPLOYPATH/"
    - /bin/cp -R shoppingzonebd "$DEPLOYPATH/"
    - /bin/cp -R kbenterprise "$DEPLOYPATH/"
    - /bin/cp -R kbdealer "$DEPLOYPATH/"