deployment:
  tasks:
    - export DEPLOYPATH=/home/jswplvao/piconetit.com/pos
    - /bin/cp -R maxmarketing "$DEPLOYPATH/"
    - /bin/cp -R basharair "$DEPLOYPATH/"
    - /bin/cp -R lubabahajj "$DEPLOYPATH/"
    - /bin/cp -R shoppingzonebd "$DEPLOYPATH/"
    - /bin/cp -R kbenterprise "$DEPLOYPATH/"
    - /bin/cp -R kbdealer "$DEPLOYPATH/"
    - /bin/cp -R mushfiqtest "$DEPLOYPATH/"
    - /bin/cp -R testpos "$DEPLOYPATH/"
    - /bin/cp -R hajjdemo "$DEPLOYPATH/"
    - /bin/cp -R muttakihajj "$DEPLOYPATH/"
    - /bin/cp -R msenayet "$DEPLOYPATH/"
    - /bin/cp -R tradingdemo "$DEPLOYPATH/"